---
packages:
- firewalld


firewalld:
- service: https
  zone: public
  permanent: yes
  state: enabled
- service: http
  zone: public
  permanent: yes
  state: enabled
- service: ssh
  zone: public
  permanent: yes
  state: enabled


ssh_user: jitsi