---

- hosts: localhost 
  connection: local
  gather_facts: no
  user: root
  vars_prompt:
    - name: hostname
      prompt: "What will be the FQDN of your vm?" 
      private: no

  tasks:

  - name: Create a basic server
    hcloud_server:
        name: '{{ hostname }}'
        server_type: '{{ hcloud_server_type }}'
        location: '{{ hcloud_location }}'
        image: '{{ hcloud_image }}'
        state: present
        ssh_keys: '{{ ssh_keys }}'
    register: server
    tags: [ always ]

  - name: Display vm info 
    debug:
      msg: "{{ server }}"

  - name: Register vm_ip and dns_truth for FQDN
    set_fact:
      vm_ip: "{{ server.hcloud_server.ipv4_address }}"
      dns_truth: "{{ lookup('dig', '{{ hostname }}.', 'qtype=A') }}"
    tags: [ always ]

  - name: Make sure DNS records are in place for use with letsencrypt certificate 
    debug:
      msg: "Please create DNS A record: {{ hostname }}. 60  IN  A  {{ vm_ip }} and a wilcard A record: *.{{ hostname }}. 60  IN  A  {{ vm_ip }}"
    until: dns_truth == vm_ip
    retries: 6
    delay: 10
    ignore_errors: true

  - name: Add host to inventory
    add_host:
      hostname: "{{ hostname }}"
      groups: "jitsi"
      ansible_host: "{{ vm_ip }}"
    tags: [ always ]
 
- hosts: jitsi 
  gather_facts: no
  user: root

  roles:
    - common
    - jitsi-meet
      

    #To do: get ip address and make sure FQDN resolves