---

- hosts: localhost 
  connection: local
  gather_facts: no
  user: root

  tasks:

  - name: Create a basic server
    hcloud_server:
        #api_token: "{{ hcloud_token }}"
        name: test.ubuntu-laptop.nl
        server_type: cx11
        image: ubuntu-18.04
        state: present
        ssh_keys: '{{ ssh_keys }}'
    register: server