---

- hosts: localhost 
  connection: local
  gather_facts: no
  user: root
  vars_prompt:
    - name: hostname
      prompt: "What will be the FQDN of your vm?" 
      private: no

  tasks:

  - name: Create a basic server
    hcloud_server:
        #api_token: "{{ hcloud_token }}"
        name: '{{ hostname }}'
        server_type: cx11
        image: ubuntu-18.04
        state: present
        ssh_keys: '{{ ssh_keys }}'
    register: server